name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main", "ci-cd" ]
  pull_request:
    branches: [ "main", "ci-cd" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild clean build analyze
