name: Xcode - Build and Analyze

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    env:
        CODE_SIGNING_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        CODE_SIGNING_ALLOWED: "NO"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild clean build analyze
      - name: Upload binary to a release
        uses: Shopify/upload-to-release@v2
        with:
            name: JimmyPlus
            path: /Users/runner/work/JimmyPlus/JimmyPlus/build/Release/jimmy.app/Contents/MacOS/jimmy
            repo-token: ${{ secrets.GITHUB_TOKEN }}
